[theme]
base = "dark"
primaryColor = "#0284C7"
backgroundColor = "#0B0F19"
secondaryBackgroundColor = "#111827"
textColor = "#F9FAFB"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true